---
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  -   id: check-yaml
  -   id: end-of-file-fixer
  -   id: trailing-whitespace
-   repo: https://github.com/tekwizely/pre-commit-golang
    rev: v1.0.0-rc.1
    hooks:
      - id: go-vet-repo-mod
        name: go-vet
      - id: go-mod-tidy-repo
        name: go-mod-tidy
- repo: https://github.com/segmentio/golines
  rev: v0.11.0
  hooks:
  - id: golines
- repo: https://github.com/golangci/golangci-lint
  rev: v1.53.3
  hooks:
  - id: golangci-lint
- repo: local
  hooks:
    - id: go-fmt
      name: go-fmt
      description: Runs `gofmt` on Go files
      language: system
      entry: gofmt -w
      types: [go]
    - id: goimports
      name: goimports
      description: Reorganise import statements
      language: system
      entry: goimports -l -w
      types: [go]
-   repo: https://github.com/sco1/brie-commit
    rev: v1.1.0
    hooks:
    -   id: brie-commit
